default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: contabancaria_development

test:
  <<: *default
  database: contabancaria_test

production:
  <<: *default
  database: contabancaria_production
  username: contabancaria
  password: <%= ENV['CONTABANCARIA_DATABASE_PASSWORD'] %>
